"""소스 검색용 Chrome 프로필과 다운로드 쿠키를 안전하게 공유한다."""
from __future__ import annotations

import os
import sqlite3
import threading
import time
from pathlib import Path

BROWSER_LOCK = threading.Lock()

PLATFORMS = {
    "tiktok": {
        "label": "TikTok",
        "url": "https://www.tiktok.com/login?lang=ko-KR",
        "domains": ("tiktok.com",),
        "cookies": ("sessionid", "sessionid_ss", "sid_guard"),
    },
    "douyin": {
        "label": "Douyin",
        "url": "https://www.douyin.com/",
        "domains": ("douyin.com",),
        "cookies": ("sessionid", "sessionid_ss", "sid_guard"),
    },
    "xiaohongshu": {
        "label": "Xiaohongshu",
        "url": "https://www.xiaohongshu.com/",
        "domains": ("xiaohongshu.com", "xhslink.com"),
        "cookies": ("web_session",),
    },
    "youtube": {
        "label": "YouTube",
        "url": "https://www.youtube.com/",
        "domains": ("youtube.com", "google.com"),
        "cookies": ("SAPISID", "__Secure-1PAPISID", "__Secure-3PAPISID", "LOGIN_INFO"),
    },
}


def _platform_rows(cookies: list[dict]) -> list[dict]:
    rows = []
    for key, spec in PLATFORMS.items():
        found = any(
            any(domain in str(cookie.get("domain", "")).lower() for domain in spec["domains"])
            and cookie.get("name") in spec["cookies"]
            and bool(cookie.get("value") or cookie.get("has_value"))
            for cookie in cookies
        )
        rows.append({"id": key, "label": spec["label"], "connected": found})
    return rows


def profile_cookie_status(profile_dir: Path) -> list[dict]:
    """복호화 없이 쿠키의 도메인·이름·값 존재 여부만 검사한다."""
    db = profile_dir / "Default" / "Cookies"
    if not db.is_file():
        return _platform_rows([])
    try:
        conn = sqlite3.connect(f"file:{db}?mode=ro", uri=True, timeout=.25)
        records = conn.execute(
            "SELECT host_key, name, length(value) + length(encrypted_value) FROM cookies"
        ).fetchall()
        conn.close()
        cookies = [{"domain": host, "name": name, "has_value": size > 0} for host, name, size in records]
    except sqlite3.Error:
        return _platform_rows([])
    return _platform_rows(cookies)


def export_cookies(cookies: list[dict], target: Path) -> None:
    """Playwright 쿠키를 yt-dlp가 읽는 Netscape 형식으로 원자적으로 저장한다."""
    target.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Netscape HTTP Cookie File", "# Generated by hotpost; do not share this file."]
    now = int(time.time())
    for cookie in cookies:
        domain = str(cookie.get("domain", "")).replace("\t", "").replace("\n", "")
        name = str(cookie.get("name", "")).replace("\t", "").replace("\n", "")
        value = str(cookie.get("value", "")).replace("\t", "").replace("\n", "")
        if not domain or not name or not value:
            continue
        expires = int(cookie.get("expires") or 0)
        if expires > 0 and expires <= now:
            continue
        prefix = "#HttpOnly_" if cookie.get("httpOnly") else ""
        lines.append("\t".join((prefix + domain, "TRUE" if domain.startswith(".") else "FALSE",
                                str(cookie.get("path") or "/"), "TRUE" if cookie.get("secure") else "FALSE",
                                str(max(0, expires)), name, value)))
    temp = target.with_suffix(target.suffix + ".tmp")
    temp.write_text("\n".join(lines) + "\n", encoding="utf-8")
    os.chmod(temp, 0o600)
    temp.replace(target)
    os.chmod(target, 0o600)
