/* Production studio: immutable versions, explicit approvals, local draft recovery. */
(() => {
  'use strict';
  const $ = (s, p=document) => p.querySelector(s);
  const esc = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const labels={preparing:'자료 준비',script_review:'대본 검토',voice_generating:'음성 생성',voice_review:'음성 검토',editing:'편집 중',draft_review:'초안 검토',attention:'확인 필요'};
  const order={preparing:0,script_review:1,voice_generating:2,voice_review:2,editing:3,draft_review:4,attention:0};
  let tasks=[], selectedId=new URLSearchParams(location.search).get('work'), filter='all', tab='script', dirty=false, saving=false, timer, saveTimer, lastRevision=-1, activeEditId=null, initialSelection=true;
  const current=()=>tasks.find(t=>t.id===selectedId);
  const revision=(t, collection, id)=>t[collection].find(r=>r.id===id);
  const time = n => `${Math.floor(n/60).toString().padStart(2,'0')}:${(n%60).toFixed(1).padStart(4,'0')}`;
  const date = n => new Date(n*1000).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'});
  function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(timer);timer=setTimeout(()=>$('#toast').hidden=true,4500);}
  async function api(path,body){const r=await fetch('/api/studio'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(data.error||'요청 실패');return data;}
  function updateTask(t){const index=tasks.findIndex(x=>x.id===t.id);if(index>=0)tasks[index]=t;else tasks.unshift(t);renderList();}
  async function action(kind,data={},options={}){
    const t=current();if(!t)return;
    try{const result=await api(`/${t.id}/${kind}`,{revision:t.revision,...data});updateTask(result);if(!options.quiet){toast(options.message||'저장했습니다.');renderDetail();}return result;}
    catch(e){toast(e.message);if(!options.quiet)await refresh();throw e;}
  }
  function renderList(){
    $('#total-count').textContent=tasks.length;$('#rail-count').textContent=tasks.length;
    const script=tasks.filter(t=>t.status==='script_review').length, voice=tasks.filter(t=>t.status==='voice_review').length, draft=tasks.filter(t=>t.status==='draft_review').length;
    const running=tasks.filter(t=>['preparing','voice_generating','editing'].includes(t.status)).length;
    $('#overview').innerHTML=[['대본 검토',script,'추천 대본을 확인해 주세요','featured'],['음성 검토',voice,'듣고 다음 단계로 넘기세요',''],['초안 검토',draft,'영상의 마지막 디테일을 확인하세요',''],['진행 중',running,'준비가 끝나면 검토함에 표시됩니다','']].map(([label,note,hint,cls])=>`<div class="metric ${cls}"><span>${label}</span><strong>${note}<small> 편</small></strong><small>${hint}</small></div>`).join('');
    const q=$('#search').value.trim().toLowerCase();
    const visible=tasks.filter(t=>(!q||(t.title+' '+t.shortcode).toLowerCase().includes(q))&&(filter==='all'||filter==='review'&&t.status.endsWith('_review')||filter==='running'&&['preparing','voice_generating','editing'].includes(t.status)||filter==='attention'&&(t.status==='attention'||t.error)));
    $('#work-list').innerHTML=visible.length?visible.map(t=>`<button class="work-card ${t.id===selectedId?'current':''}" data-work="${t.id}"><div class="card-top"><span class="pill ${t.status}">${labels[t.status]||t.status}</span><span class="card-code">${esc(t.shortcode)}</span></div><h3>${esc(t.title)}</h3><div class="mini-steps">${[0,1,2,3,4].map(n=>`<i class="${n<=order[t.status]?'done':''}"></i>`).join('')}</div><div class="muted">${esc(t.error?'확인 후 다시 시도할 수 있어요':t.message)}</div><div class="card-bottom"><span>${date(t.updated)} 저장 · ${t.scripts.length}개 대본 버전</span><b>작업 열기 →</b></div></button>`).join(''):`<div class="empty"><h2>${tasks.length?'해당하는 작업이 없습니다':'첫 번째 영상을 준비해 볼까요?'}</h2><p>소재 탐색에서 여러 게시물을 선택해 제작실에 추가하세요.<br>대본과 음성을 승인한 뒤 영상 제작이 시작됩니다.</p><a href="index.html" class="button primary">소재 탐색하기 →</a></div>`;
  }
  function renderDetail(){
    const t=current();const panel=$('#detail');panel.hidden=!t;if(!t)return;
    lastRevision=t.revision;
    const selectedEdit=revision(t,'edits',activeEditId)||revision(t,'edits',t.edit_id);
    panel.innerHTML=`<div class="detail-head"><div><div class="eyebrow">WORKSPACE / ${esc(t.shortcode)}</div><h2>${esc(t.title)}</h2><p>작업과 모든 버전이 자동 저장됩니다 · 마지막 저장 ${date(t.updated)}</p></div><div class="detail-actions"><button class="secondary" data-action="capcut" ${selectedEdit?'':'disabled'}>${selectedEdit?'CapCut에서 직접 편집 ↗':'CapCut · 초안 생성 후 이용'}</button></div></div>
    <div class="stepper"><button data-tab="script" class="${tab==='script'?'on':''}">1. 대본 검토 ${t.approved_script_id?'✓':''}</button><span class="connector">→</span><button data-tab="voice" class="${tab==='voice'?'on':''}">2. 음성 검토 ${t.approved_voice_id?'✓':''}</button><span class="connector">→</span><button data-tab="edit" class="${tab==='edit'?'on':''}">3. 초안 검토</button></div>
    ${t.error?`<div class="notice error">${esc(t.error)} <button class="quiet" data-action="retry">중단 단계부터 재시도</button></div>`:''}
    ${tab==='script'?scriptPanel(t):tab==='voice'?voicePanel(t):editPanel(t,selectedEdit)}`;
    const textarea=$('#script-editor');
    if(textarea){const local=JSON.parse(localStorage.getItem('studio-draft-'+t.id)||'null');if(local&&local.base===t.script_id&&local.text!==textarea.value){textarea.value=local.text;dirty=true;$('#save-status').textContent='이 기기에 저장된 수정 내용 복구됨';}}
    const video=$('#preview-video');if(video)video.addEventListener('timeupdate',()=>{const n=video.currentTime;panel.querySelectorAll('.beat').forEach(b=>b.classList.toggle('active',n>=Number(b.dataset.start)&&n<Number(b.dataset.end)));});
  }
  function scriptPanel(t){
    const s=revision(t,'scripts',t.script_id);
    if(!s)return `<div class="panel pending"><span class="spinner"></span><h3>자료와 추천 대본을 준비하고 있어요</h3>자료 확보가 완료되면 여기에서 대본을 검토할 수 있습니다.</div>`;
    const proposals=t.proposals.filter(p=>p.script_id===s.id);
    return `<div class="detail-grid"><div class="panel"><h3>원본과 참고 자료</h3><p class="muted">원본의 매력을 참고하되 새로운 문장으로 구성합니다.</p><div class="reference-box">${esc(t.original_text)}</div><div class="source-strip">${t.sources.slice(0,6).map((src,i)=>`<video src="${esc(src.url)}#t=1" controls preload="metadata" title="소스 ${i+1}"></video>`).join('')}</div><a class="muted" href="https://www.instagram.com/p/${encodeURIComponent(t.shortcode)}/" target="_blank" rel="noopener">원본 게시물 보기 ↗</a><div class="subsection"><h3>대본 버전</h3><div class="version-list">${t.scripts.slice().reverse().map((v,i)=>`<div class="version-item"><div>버전 ${t.scripts.length-i} ${v.id===s.id?'<span class="pill draft_review">현재</span>':''}<br><small>${date(v.created)} · ${{manual:'직접 수정',recommended:'AI 추천',ai_proposal:'AI 수정',restored:'이전 버전 복원'}[v.origin]||v.origin}</small></div><button data-restore="${v.id}" ${v.id===s.id?'disabled':''}>복원</button></div>`).join('')}</div></div></div>
    <div class="panel"><div class="row"><h3>추천 대본</h3><span class="pill ${t.approved_script_id===s.id?'draft_review':'script_review'}">${t.approved_script_id===s.id?'승인 완료':'검토 대기'}</span></div><p class="muted">이 대본을 들으면, 제품이 더 궁금해질까요?</p><textarea id="script-editor" aria-label="대본 편집">${esc(s.text)}</textarea><div class="editor-footer"><small id="save-status">저장됨 · ${s.text.length}자</small><button class="quiet" data-action="save-script">저장</button><button class="primary" data-action="approve-script" ${t.approved_script_id===s.id?'disabled':''}>대본 승인 · 음성 생성 →</button></div>
    <div class="subsection"><h3>AI와 함께 다듬기</h3><p class="muted">수정안을 비교한 뒤 적용합니다. 직접 고친 대본은 보존됩니다.</p><textarea class="request" id="script-request" placeholder="예: 첫 문장을 더 궁금하게, 설명은 자연스러운 말투로 바꿔줘" aria-label="대본 AI 수정 요청"></textarea><div class="editor-footer"><small>${t.jobs.some(j=>j.kind==='proposal'&&['queued','running'].includes(j.status))?'AI가 수정안을 준비 중입니다…':''}</small><button class="secondary" data-action="propose-script">수정안 만들기</button></div></div>
    ${proposals.slice().reverse().map(p=>`<div class="proposal"><h3>${esc(p.summary)}</h3><div class="editor-footer"><small>직접 비교한 뒤 적용합니다</small><button class="secondary" data-compare="${p.id}">변경안 비교</button></div></div>`).join('')}</div></div>`;
  }
  function voicePanel(t){
    const s=revision(t,'scripts',t.script_id),v=revision(t,'voices',t.voice_id);
    const busy=t.status==='voice_generating';
    return `<div class="detail-grid"><div class="panel"><h3>승인 대본</h3><p class="muted">이 버전의 대본으로 생성한 음성입니다.</p><div class="reference-box">${esc(s?.text||'대본을 먼저 승인해 주세요.')}</div><div class="subsection"><h3>음성 이력 · 전후 비교</h3><div class="version-list">${t.voices.slice().reverse().map((a,i)=>`<div class="version-item" style="display:block"><div class="row"><b>음성 ${t.voices.length-i}</b><small>${a.script_id===t.script_id?'현재 대본':'이전 대본'} · ${a.duration.toFixed(1)}초</small></div><audio controls preload="none" src="${esc(a.path_url)}" style="width:100%;height:34px;margin-top:10px"></audio></div>`).join('')||'<p class="muted">생성된 음성이 여기에 보관됩니다.</p>'}</div></div></div>
    <div class="panel"><div class="row"><h3>내 목소리 확인하기</h3><span class="pill voice_review">${busy?'음성 생성 중':v?'청취 후 승인':'대본 승인 대기'}</span></div><p class="muted">목소리와 발음, 문장 사이의 호흡을 확인해 주세요.</p>
    ${busy?'<div class="pending"><span class="spinner"></span><h3>내 목소리로 읽고 있어요</h3>창을 닫아도 작업은 계속됩니다. 다른 대본을 먼저 검토해도 됩니다.</div>':v?`<div class="voice-player"><div class="waveform">${Array.from({length:42},(_,i)=>`<i style="height:${10+Math.abs(Math.sin(i*1.8))*34}px"></i>`).join('')}</div><audio id="voice-player" controls preload="metadata" src="${esc(v.path_url)}"></audio><h4>음성 ${t.voices.indexOf(v)+1} · ${v.duration.toFixed(1)}초</h4><p>최종 사용 음성 · ${v.speed.toFixed(2)}배속 · 승인 이후 속도를 변경하지 않습니다</p></div><div class="editor-footer"><small>${t.approved_voice_id===v.id?'이 음성으로 편집 중이거나 초안이 준비되었습니다.':'괜찮다면 영상 편집을 시작하세요.'}</small><button class="primary" data-action="approve-voice" ${t.approved_voice_id===v.id?'disabled':''}>음성 승인 · 영상 편집 →</button></div>`:'<div class="pending">대본을 승인하면 음성 생성이 시작됩니다.</div>'}
    <div class="subsection"><h3>다시 만들어 듣기</h3><p class="muted">기존 VoiceBench 목소리·엔진 설정을 유지합니다. 속도는 승인 전 음성에 적용됩니다. 동일 대본은 기존 생성 결과를 재사용할 수 있습니다. 구간별 재생성·감정 지시는 현재 제공하지 않습니다.</p><div class="editor-footer"><label>말하기 속도 <select id="voice-speed"><option value="1">기본 1.00×</option><option value=".95">여유롭게 0.95×</option><option value="1.05">조금 빠르게 1.05×</option><option value="1.12">빠르게 1.12×</option></select></label><button class="secondary" data-action="regenerate-voice" ${busy||!t.approved_script_id?'disabled':''}>속도 적용 · 음성 다시 준비</button></div></div></div></div>`;
  }
  function editPanel(t,e){
    if(!e)return `<div class="panel pending">${t.status==='editing'?'<span class="spinner"></span><h3>자막과 장면을 맞추고 있어요</h3>승인한 음성에 맞춰 싱크와 강조를 구성합니다.':'<h3>음성을 승인하면 초안을 만들어요</h3>대본과 음성 검토를 먼저 완료해 주세요.'}</div>`;
    const p=e.plan,busy=t.status==='editing',historical=e.id!==t.edit_id;
    return `<div class="preview-grid"><div class="preview-player"><video id="preview-video" src="${esc(e.preview_url)}" controls playsinline preload="metadata" poster="${esc(e.cover_url)}"></video><p>첫 프레임 썸네일 포함 · ${e.duration.toFixed(1)}초<br>초안 ${t.edits.indexOf(e)+1} / ${t.edits.length} · ${e.review_count}개 장면 확인 필요</p><a class="button secondary" href="${esc(e.preview_url)}" download="shorts-preview.mp4" style="display:block;text-align:center">영상 다운로드 ↓</a></div><div class="panel"><div class="row"><h3>초안 검토</h3><select id="edit-version" aria-label="편집 버전">${t.edits.map((a,i)=>`<option value="${a.id}" ${a.id===e.id?'selected':''}>초안 ${i+1} · ${date(a.created)} ${a.id===t.edit_id?'(현재)':'(이전)'}</option>`).join('')}</select></div>
    ${historical?'<div class="notice">이전 버전을 보고 있습니다. 구간 수정은 현재 버전에서 할 수 있습니다.</div>':''}
    ${busy?'<div class="notice"><span class="spinner"></span> 새 버전을 만드는 동안 현재 초안을 계속 볼 수 있습니다.</div>':''}
    ${t.candidate_requests?.length?`<div class="notice">장면 교체 요청을 확인했습니다. 아래 표시된 구간의 후보를 비교해 선택하세요.</div>`:''}${p.warnings.map(w=>`<div class="notice">${esc(w)}</div>`).join('')}
    <p class="muted">${esc(p.preview_limitations.join(' '))}</p>
    <div class="subsection"><h3>이 구간, 이렇게 바꿔주세요</h3><div class="timing"><label>시작 <input id="selection-start" type="number" min="0" step=".01" value="0"></label><label>끝 <input id="selection-end" type="number" min="0" max="${p.duration}" step=".01" value="${p.duration.toFixed(2)}"></label><button class="quiet" data-action="select-playing">현재 장면 선택</button></div><textarea class="request" id="edit-request" placeholder="예: 이 장면은 다른 후보를 보여주고, 마지막 대박이에요 부분은 더 강하게 강조해줘" aria-label="영상 구간 수정 요청"></textarea><div class="editor-footer"><small>장면 교체는 후보를 보고 직접 선택합니다</small><button class="secondary" data-action="request-edit" ${busy||historical?'disabled':''}>수정 요청</button></div></div>
    <div class="subsection"><div class="row"><h3>장면 · 자막 · 강조</h3><span class="muted">시간을 누르면 해당 구간으로 이동</span></div>
    ${p.beats.map(b=>{const c=p.cues.find(c=>c.id===b.cue_id);return `<article class="beat ${t.candidate_requests?.includes(b.id)?'requested':''}" data-beat="${b.id}" data-start="${b.start}" data-end="${b.end}"><div class="beat-head"><button class="time-button" data-seek="${b.start}">${time(b.start)} – ${time(b.end)}</button>${b.needs_review?'<span class="pill review">대체 장면 · 확인 필요</span>':'<span class="pill draft_review">대사와 대응</span>'}</div><h4>${esc(c.text)}</h4><p>${esc(b.reason)}${t.candidate_requests?.includes(b.id)?'<br><b>장면 교체 요청 · 후보를 선택해 주세요</b>':''}</p><div class="beat-controls"><label class="muted">강조 <select data-emphasis="${b.id}" ${busy||historical?'disabled':''}><option value="0" ${b.emphasis===0?'selected':''}>없음</option><option value="1" ${b.emphasis===1?'selected':''}>분명하게</option><option value="2" ${b.emphasis===2?'selected':''}>강하게</option></select></label><button class="secondary" data-candidates="${b.id}" ${busy||historical?'disabled':''}>장면 후보 ${b.options.length}개 보기</button></div><details><summary class="muted" style="margin-top:12px;cursor:pointer">자막 문구·싱크 미세 조정 ${c.needs_review?'· 정렬 확인 필요':''}</summary><div class="timing"><input class="caption" data-cue-text="${b.id}" value="${esc(c.text)}" aria-label="자막 문구"></div><div class="timing"><label>시작 <input data-cue-start="${b.id}" type="number" step=".01" value="${c.start.toFixed(2)}"></label><label>끝 <input data-cue-end="${b.id}" type="number" step=".01" value="${c.end.toFixed(2)}"></label><button class="quiet" data-cue-save="${b.id}" ${busy||historical?'disabled':''}>구간 저장</button></div></details></article>`;}).join('')}</div></div></div>`;
  }
  async function saveScript(){const t=current(),input=$('#script-editor');if(!t||!input||!dirty)return;if(saving){await saving;if(dirty)return saveScript();return;}const text=input.value;saving=(async()=>{const saved=await action('save-script',{text},{quiet:true});dirty=input.value!==text;if(dirty){localStorage.setItem('studio-draft-'+t.id,JSON.stringify({base:saved.script_id,text:input.value}));}else{localStorage.removeItem('studio-draft-'+t.id);}$('#save-status').textContent=dirty?'수정 중…':`저장됨 · ${text.length}자`;})();try{await saving;}finally{saving=false;}}
  function showCandidates(beatId){const t=current(),e=revision(t,'edits',t.edit_id),b=e.plan.beats.find(b=>b.id===beatId);$('#candidate-caption').textContent=`“${b.text}” · 실제 확보된 장면 중에서 선택하세요.`;$('#candidates').innerHTML=b.options.map((o,i)=>{const s=e.plan.shots.find(s=>s.id===o.shot_id);return `<article class="candidate"><video src="${esc(s.video_url)}#t=${s.start},${s.end}" poster="${esc(s.thumbnail_url)}" controls preload="none"></video><h4>후보 ${i+1} <span class="pill ${o.relation==='direct'?'draft_review':'review'}">${{direct:'직접 대응',context:'제품 맥락',illustration:'대체 장면'}[o.relation]}</span></h4><p>${esc(s.observation)}<br>${esc(o.reason)}</p><button class="primary" data-choose-shot="${s.id}" data-for-beat="${b.id}">${b.selected_shot_id===s.id?'현재 장면':'이 장면 사용'}</button></article>`;}).join('');$('#candidate-dialog').showModal();}
  document.addEventListener('click',async event=>{const el=event.target.closest('button');if(!el)return;try{
    if(el.dataset.work){if(dirty)await saveScript();selectedId=el.dataset.work;activeEditId=null;const t=current();tab=t.status.includes('voice')?'voice':t.edit_id?'edit':'script';history.replaceState(null,'','?work='+selectedId);renderList();renderDetail();$('#detail').scrollIntoView({behavior:'smooth',block:'start'});}
    if(el.dataset.filter){filter=el.dataset.filter;$('#filters').querySelectorAll('button').forEach(b=>b.classList.toggle('selected',b===el));renderList();}
    if(el.dataset.tab){if(dirty)await saveScript();tab=el.dataset.tab;renderDetail();}
    if(el.dataset.seek){$('#preview-video').currentTime=Math.ceil(Number(el.dataset.seek)*30)/30+.001;}
    if(el.dataset.candidates)showCandidates(el.dataset.candidates);
    if(el.dataset.restore){await action('restore-script',{script_id:el.dataset.restore});dirty=false;}
    if(el.dataset.compare){const t=current(),s=revision(t,'scripts',t.script_id),p=t.proposals.find(p=>p.id===el.dataset.compare);$('#script-comparison').innerHTML=`<p class="muted">${esc(p.summary)}</p><div class="compare"><div><b>현재 대본</b><br>${esc(s.text)}</div><div><b>AI 수정안</b><br>${esc(p.text)}</div></div><div class="editor-footer"><small>적용하면 새 버전으로 저장됩니다. 이전 대본은 복원할 수 있습니다.</small><button class="primary" data-proposal="${p.id}">이 수정안 적용</button></div>`;$('#script-dialog').showModal();}
    if(el.dataset.proposal){$('#script-dialog').close();await saveScript();await action('apply-proposal',{proposal_id:el.dataset.proposal});}
    if(el.dataset.chooseShot){$('#candidate-dialog').close();await action('revise-edit',{edit_id:current().edit_id,changes:[{beat_id:el.dataset.forBeat,shot_id:el.dataset.chooseShot}]},{message:'선택한 장면으로 새 초안을 만듭니다.'});}
    if(el.dataset.cueSave){const id=el.dataset.cueSave;await action('revise-edit',{edit_id:current().edit_id,changes:[{beat_id:id,text:$(`[data-cue-text="${id}"]`).value,start:Number($(`[data-cue-start="${id}"]`).value),end:Number($(`[data-cue-end="${id}"]`).value)}]});}
    const kind=el.dataset.action;if(!kind)return;el.disabled=true;
    if(kind==='save-script'){await saveScript();renderDetail();}
    else if(kind==='approve-script'){await saveScript();await action(kind,{script_id:current().script_id});tab='voice';renderDetail();}
    else if(kind==='propose-script'){const request=$('#script-request').value;await saveScript();await action(kind,{request},{message:'AI 수정안을 준비합니다.'});}
    else if(kind==='approve-voice'){await action(kind,{voice_id:current().voice_id});tab='edit';renderDetail();}
    else if(kind==='regenerate-voice')await action(kind,{script_id:current().script_id,speed:Number($('#voice-speed').value)});
    else if(kind==='retry')await action(kind,{}, {message:'중단된 단계를 이어서 실행합니다.'});
    else if(kind==='capcut')await action('open-capcut',{edit_id:activeEditId||current().edit_id},{message:'CapCut 초안을 준비합니다. 기존 손편집본은 보존됩니다.'});
    else if(kind==='select-playing'){const e=revision(current(),'edits',activeEditId||current().edit_id);const n=Math.min($('#preview-video').currentTime,e.plan.duration-.001);const b=e.plan.beats.find(b=>b.start<=n&&n<b.end);if(b){$('#selection-start').value=b.start.toFixed(2);$('#selection-end').value=b.end.toFixed(2);}}
    else if(kind==='request-edit')await action(kind,{edit_id:current().edit_id,request:$('#edit-request').value,start:Number($('#selection-start').value),end:Number($('#selection-end').value)},{message:'선택한 구간의 수정 요청을 처리합니다.'});
    el.disabled=false;
  }catch(_){el.disabled=false;}});
  document.addEventListener('input',event=>{if(event.target.id==='script-editor'){dirty=true;const t=current();localStorage.setItem('studio-draft-'+t.id,JSON.stringify({base:t.script_id,text:event.target.value}));$('#save-status').textContent='수정 중 · 자동 저장 대기';$('[data-action="approve-script"]').disabled=false;clearTimeout(saveTimer);saveTimer=setTimeout(()=>saveScript().catch(()=>{}),1200);}if(event.target.id==='search')renderList();});
  document.addEventListener('change',async event=>{try{if(event.target.dataset.emphasis)await action('revise-edit',{edit_id:current().edit_id,changes:[{beat_id:event.target.dataset.emphasis,emphasis:Number(event.target.value)}]});if(event.target.id==='edit-version'){activeEditId=event.target.value;renderDetail();}}catch(_){}});
  $('#close-candidates').onclick=()=>$('#candidate-dialog').close();$('#close-script-dialog').onclick=()=>$('#script-dialog').close();
  window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});
  async function refresh(){try{const data=await api('');tasks=data.tasks;$('#connection').hidden=true;renderList();const t=current();if(t&&initialSelection){tab=t.status.includes('voice')?'voice':t.edit_id?'edit':'script';initialSelection=false;}if(t&&t.revision!==lastRevision&&!dirty&&!document.activeElement.matches('textarea,input,select')&&![...document.querySelectorAll('video,audio')].some(m=>!m.paused)){renderDetail();}if(!selectedId&&tasks.length){selectedId=tasks[0].id;tab=tasks[0].status.includes('voice')?'voice':tasks[0].edit_id?'edit':'script';renderDetail();}}catch(e){$('#connection').textContent='연결을 확인하고 있습니다. 저장된 작업과 입력 내용은 보존됩니다. '+e.message;$('#connection').hidden=false;}}
  refresh();setInterval(refresh,3000);
})();
